/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Assignment = IDL.Record({
  'recipient' : IDL.Principal,
  'santa' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const Profile = IDL.Record({
  'name' : IDL.Text,
  'wishList' : IDL.Text,
  'registrationTime' : Time,
});
export const Round = IDL.Record({
  'assignments' : IDL.Vec(Assignment),
  'deadline' : Time,
  'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, Profile)),
});
export const Stage = IDL.Variant({
  'resolution' : IDL.Null,
  'submission' : IDL.Null,
});
export const StreamingToken = IDL.Record({
  'resource' : IDL.Text,
  'index' : IDL.Nat,
});
export const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
});
export const StreamingCallbackHttpResponse = IDL.Record({
  'token' : IDL.Opt(StreamingToken),
  'body' : IDL.Vec(IDL.Nat8),
});
export const StreamingCallback = IDL.Func(
    [StreamingToken],
    [StreamingCallbackHttpResponse],
    ['query'],
  );
export const StreamingStrategy = IDL.Variant({
  'Callback' : IDL.Record({
    'token' : StreamingToken,
    'callback' : StreamingCallback,
  }),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HeaderField),
  'streaming_strategy' : IDL.Opt(StreamingStrategy),
  'status_code' : IDL.Nat16,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteParticipant' : IDL.Func([IDL.Principal], [], []),
  'deleteParticipantByName' : IDL.Func([IDL.Text], [], []),
  'deletePastRound' : IDL.Func([Time], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAssignmentNames' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeadline' : IDL.Func([], [Time], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getMyAssignment' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPastRounds' : IDL.Func([], [IDL.Vec(IDL.Tuple(Time, Round))], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getStage' : IDL.Func([], [Stage], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'httpStreamingCallback' : IDL.Func(
      [StreamingToken],
      [
        IDL.Record({
          'token' : IDL.Opt(StreamingToken),
          'body' : IDL.Vec(IDL.Nat8),
        }),
      ],
      ['query'],
    ),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'listParticipantNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetRound' : IDL.Func([], [], []),
  'rollbackToSubmissionStage' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDeadline' : IDL.Func([Time], [], []),
  'triggerResolution' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Assignment = IDL.Record({
    'recipient' : IDL.Principal,
    'santa' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const Profile = IDL.Record({
    'name' : IDL.Text,
    'wishList' : IDL.Text,
    'registrationTime' : Time,
  });
  const Round = IDL.Record({
    'assignments' : IDL.Vec(Assignment),
    'deadline' : Time,
    'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, Profile)),
  });
  const Stage = IDL.Variant({
    'resolution' : IDL.Null,
    'submission' : IDL.Null,
  });
  const StreamingToken = IDL.Record({
    'resource' : IDL.Text,
    'index' : IDL.Nat,
  });
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
  });
  const StreamingCallbackHttpResponse = IDL.Record({
    'token' : IDL.Opt(StreamingToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const StreamingCallback = IDL.Func(
      [StreamingToken],
      [StreamingCallbackHttpResponse],
      ['query'],
    );
  const StreamingStrategy = IDL.Variant({
    'Callback' : IDL.Record({
      'token' : StreamingToken,
      'callback' : StreamingCallback,
    }),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteParticipant' : IDL.Func([IDL.Principal], [], []),
    'deleteParticipantByName' : IDL.Func([IDL.Text], [], []),
    'deletePastRound' : IDL.Func([Time], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAssignmentNames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeadline' : IDL.Func([], [Time], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getMyAssignment' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPastRounds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, Round))],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getStage' : IDL.Func([], [Stage], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'httpStreamingCallback' : IDL.Func(
        [StreamingToken],
        [
          IDL.Record({
            'token' : IDL.Opt(StreamingToken),
            'body' : IDL.Vec(IDL.Nat8),
          }),
        ],
        ['query'],
      ),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listParticipantNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetRound' : IDL.Func([], [], []),
    'rollbackToSubmissionStage' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDeadline' : IDL.Func([Time], [], []),
    'triggerResolution' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };