/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment { 'recipient' : Principal, 'santa' : Principal }
export interface FileReference { 'hash' : string, 'path' : string }
export type HeaderField = [string, string];
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface Profile {
  'name' : string,
  'wishList' : string,
  'registrationTime' : Time,
}
export interface Round {
  'assignments' : Array<Assignment>,
  'deadline' : Time,
  'profiles' : Array<[Principal, Profile]>,
}
export type Stage = { 'resolution' : null } |
  { 'submission' : null };
export type StreamingCallback = ActorMethod<
  [StreamingToken],
  StreamingCallbackHttpResponse
>;
export interface StreamingCallbackHttpResponse {
  'token' : [] | [StreamingToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = {
    'Callback' : { 'token' : StreamingToken, 'callback' : [Principal, string] }
  };
export interface StreamingToken { 'resource' : string, 'index' : bigint }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, string], undefined>,
  'deleteParticipant' : ActorMethod<[Principal], undefined>,
  'deleteParticipantByName' : ActorMethod<[string], undefined>,
  'deletePastRound' : ActorMethod<[Time], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAssignmentNames' : ActorMethod<[], Array<[string, string]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeadline' : ActorMethod<[], Time>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getMyAssignment' : ActorMethod<[], [] | [Profile]>,
  'getPastRounds' : ActorMethod<[], Array<[Time, Round]>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getStage' : ActorMethod<[], Stage>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'httpStreamingCallback' : ActorMethod<
    [StreamingToken],
    { 'token' : [] | [StreamingToken], 'body' : Uint8Array }
  >,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listParticipantNames' : ActorMethod<[], Array<string>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'resetRound' : ActorMethod<[], undefined>,
  'rollbackToSubmissionStage' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDeadline' : ActorMethod<[Time], undefined>,
  'triggerResolution' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];